language: c

dist: bionic

arch:
    - amd64
    - arm64

compiler:
    - gcc
#    - clang

env:
  global:
    - PACKAGE_NAME=allstarlink-asterisk

before_install:
    - export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
    - export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb

addons:
    apt:
        - debhelper
        - devscripts
        - quilt

        - zlib1g-dev
        - libreadline-gplv2-dev
        - libgsm1-dev
        - libssl-dev
        - libtonezone-dev
        - libasound2-dev
        - libpq-dev
        - unixodbc-dev
        - libpri-dev
        - libvpb-dev
#        - asl-dahdi-source
        - libnewt-dev
        - libsqlite-dev
        - libspeex-dev
        - libspeexdsp-dev
        - graphviz
        - libcurl4-openssl-dev
        - doxygen
        - gsfonts
        - libpopt-dev
        - libiksemel-dev
        - freetds-dev
        - libvorbis-dev
        - libsnmp-dev
        - libcap-dev
        - libi2c-dev
        - libjansson-dev
        - libusb-dev

install:  skip

script:
    - autoconf -V
    - cd $TRAVIS_BUILD_DIR/asterisk
#    - ./bootstrap.sh
    - ./configure
#    - debuild -b -uc -us
    - make
#   - dpkg-deb --build $PACKAGE_NAME
#   - mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION

#after_success:
#   - ls -l $PACKAGE_NAME_VERSION
#   - md5sum $PACKAGE_NAME_VERSION
#   - dpkg --contents $PACKAGE_NAME_VERSION
