language: c

dist:  xenial
#    - bionic

arch:
    - amd64
    - arm64

compiler:
    - gcc
#    - clang


addons:
    apt:
        - debhelper
        - quilt

        - zlib1g-dev
        - libreadline-gplv2-dev
        - libgsm1-dev
        - libssl-dev
        - libtonezone-dev
        - libasound2-dev
        - libpq-dev
        - unixodbc-dev
        - libpri-dev
        - libvpb-dev
#        - asl-dahdi-source
        - libnewt-dev
        - libsqlite-dev
        - libspeex-dev
        - libspeexdsp-dev
        - graphviz
        - libcurl4-openssl-dev
        - doxygen
        - gsfonts
        - libpopt-dev
        - libiksemel-dev
        - freetds-dev
        - libvorbis-dev
        - libsnmp-dev
        - libcap-dev
        - libi2c-dev
        - libjansson-dev
        - libusb-dev

install:  skip

script:
  - cd $TRAVIS_BUILD_DIR/asterisk
  - ./bootstrap.sh && ./configure
  - debuild -b -uc -us

