language: c

arch:
  - amd64
  - arm64  # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below

compiler:
  - gcc
  - clang

before_script:
- sudo apt-get install devscripts debhelper

install: skip

script:
  - cd $TRAVIS_BUILD_DIR/asterisk
  - ./bootstrap.sh && ./configure
  - debuild -b -uc -us

